### ISSUE TITLE
AssertionError and KeyError

### ISSUE THREAD

**Issue by Daotaku** [norvig/pytudes#1]
There is an error in line 61 inside grid_values def, because chars will always be 1
`assert len(chars) == 81`

Next in the line 103 there is a KeyError when hitting the "A2"
`width = 1+max(len(values[s]) for s in squares)`

I've tried it with python3 and python2 and both has the same problem

Is this intentional?

**Comment by norvig** [comment]
Oops -- a data error in the file; fixed now; thanks.
