### ISSUE TITLE
"Advent of Code 2021" is actually "Advent of Code 2020"

### ISSUE THREAD

**Issue by PedanticHacker** [norvig/pytudes#115]
@norvig, you have _Advent of Code 2020_ notebooks and you have _Advent of Code 2021_ notebooks (if you believe the hyperlink text, anyway), but following the links to the mentioned notebooks reveals that everything leads to **the one and only** *Advent of Code 2020*. 

There aren't any **_real_** _Advent of Code 2021_ notebooks, are there, Peter? Is this an early April Fools' Day prank maybe?

**Comment by norvig** [comment]
Yikes! A bad copy-paste-forget-to-edit error. Thanks for the correction!
