### ISSUE TITLE
Python3 compatibility How to Do Things with Words.ipynb 

### ISSUE THREAD

**Issue by pathcl** [norvig/pytudes#34]
Hello,

I'm trying to use 'How to Do Things with Words' notebook but... 

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-4412bcdfa1ad> in <module>()
----> 1 TEXT = file('big.txt').read()
      2 len(TEXT)

NameError: name 'file' is not defined

- I think this should be replaced to use open() instead of file().

- I was able to use 'big.txt' downloading from https://norvig.com/big.txt .Not sure if its the same.

I'll upload a PR to make it py3 compatible.

**Comment by norvig** [comment]
Good catch. Probably best to put 'big.txt', and any other such files, in the data directory (under, say, a /text subdirectory).

**Comment by agushermansyah621** [comment]
Putrapy3

**Comment by pathcl** [comment]
Closing since https://github.com/norvig/pytudes/pull/50 is merged
