### ISSUE TITLE
Loading function for loading files "count_1w.txt" is not working

### ISSUE THREAD

**Issue by pallavi-xtage** [norvig/pytudes#62]
Hi,

This function is always throwing an error.

def load_counts(filename, sep='\t'):
    """Return a Counter initialized from key-value pairs, 
    one on each line of filename."""
    C = Counter()
    for line in open(filename):
        key, count = line.split(sep)
        C[key] = int(count)
    return C

**Sometimes it is throwing an error of this type:-**
Error is in line --> 168         C[key].append(int(count))

and error is-->                   TypeError: unhashable type: 'list'

**And sometimes:-**
--> 167         key, count = line.split(sep)

ValueError: not enough values to unpack (expected 2, got 1)

I can't find the reason.Please help.I am using Python3 and have edited everything related to Python3 in this program.Please let me know the reason of above errors.

**Comment by pallavi-xtage** [comment]
I am using code of site:--
https://nbviewer.jupyter.org/url/norvig.com/ipython/How%20to%20Do%20Things%20with%20Words.ipynb

**Comment by norvig** [comment]
Could not reproduce. Code has been changed and seems to work now.
