### ISSUE TITLE
missing data/advent2018 input folder 

### ISSUE THREAD

**Issue by alessiomargan** [norvig/pytudes#63]
Hi,
missing input folder data/advent2018 in repository
Alessio 

input1 = Input(1, int)

sum(input1)
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-cee6ca99cfc7> in <module>
----> 1 input1 = Input(1, int)
      2 
      3 sum(input1)

<ipython-input-1-cb09edf26f97> in Input(day, line_parser, file_template)
     18 def Input(day, line_parser=str.strip, file_template='data/advent2018/input{}.txt'):
     19     "For this day's input file, return a tuple of each line parsed by `line_parser`."
---> 20     return mapt(line_parser, open(file_template.format(day)))
     21 
     22 def integers(text):

FileNotFoundError: [Errno 2] No such file or directory: 'data/advent2018/input1.txt'

**Comment by Bklyn** [comment]
Just noticed this myself.

**Comment by alessiomargan** [comment]
never mind
