### ISSUE TITLE
Typo: 4^9 not 9^4

### ISSUE THREAD

**Issue by iamaziz** [norvig/pytudes#85]
Perhaps, there's a typo in the number of possibilities here:
https://github.com/norvig/pytudes/blame/master/ipynb/Countdown.ipynb#L58 

It might be meant to be the other way around `4^9 = 262,144` instead of `9^4`.

![image](https://user-images.githubusercontent.com/3298308/82110692-4c14f680-970e-11ea-8b4a-b0db08e65077.png)

**Comment by norvig** [comment]
Got it, thanks!
